// frontend-svelte/src/lib/components/ModePlaylistMapper.svelte
<script>
  import { onMount, onDestroy } from 'svelte'
  import { apiGet, apiPost, apiDelete } from '$lib/api.js'

  const MODE_CONFIG = [
    { mode: 'gaming',   label: 'Gaming',   icon: '🎮' },
    { mode: 'working',  label: 'Working',  icon: '💻' },
    { mode: 'watching', label: 'Watching', icon: '🎬' },
    { mode: 'relax',    label: 'Relax',    icon: '🛋️' },
    { mode: 'social',   label: 'Party',    icon: '🎉' },
    { mode: 'movie',    label: 'Movie',    icon: '🍿' },
  ]

  const VIBES = [
    { value: '',           label: 'No vibe tag' },
    { value: 'energetic',  label: '⚡ Energetic' },
    { value: 'focus',      label: '🎯 Focus' },
    { value: 'mellow',     label: '🌙 Mellow' },
    { value: 'background', label: '🎧 Background' },
    { value: 'hype',       label: '🔥 Hype' },
  ]

  /** @type {Record<string, any[]>} */
  let mappings = {}
  /** @type {Array<{ title: string }>} */
  let favorites = []
  let mounted = true

  onMount(async () => {
    try {
      const data = await apiGet('/api/music/mode-playlists')
      if (mounted) {
        mappings = data.mappings || {}
        favorites = data.favorites || []
      }
    } catch {
      /* ignore */
    }
  })

  onDestroy(() => { mounted = false })

  // Per-mode add-row state. Keyed by mode.
  /** @type {Record<string, { title: string, vibe: string, autoPlay: boolean, saving: boolean }>} */
  let addRowState = Object.fromEntries(
    MODE_CONFIG.map(({ mode }) => [mode, { title: '', vibe: '', autoPlay: false, saving: false }])
  )

  /** @param {string} mode */
  async function handleAdd(mode) {
    const row = addRowState[mode]
    if (!row.title) return
    row.saving = true
    addRowState = { ...addRowState }
    try {
      const data = await apiPost('/api/music/mode-playlists', {
        mode,
        favorite_title: row.title,
        vibe: row.vibe || null,
        auto_play: row.autoPlay,
      })
      mappings = {
        ...mappings,
        [mode]: [
          ...(mappings[mode] || []),
          {
            id: data.id,
            mode,
            favorite_title: row.title,
            vibe: row.vibe || null,
            auto_play: row.autoPlay,
            priority: 0,
          },
        ],
      }
      addRowState[mode] = { title: '', vibe: '', autoPlay: false, saving: false }
      addRowState = { ...addRowState }
    } catch {
      row.saving = false
      addRowState = { ...addRowState }
    }
  }

  /** @param {string} mode @param {number} mappingId */
  async function handleRemove(mode, mappingId) {
    try {
      await apiDelete(`/api/music/mode-playlists/${mappingId}`)
      mappings = {
        ...mappings,
        [mode]: (mappings[mode] || []).filter((e) => e.id !== mappingId),
      }
    } catch {
      /* ignore */
    }
  }

  /** @param {string} vibe */
  function vibeLabel(vibe) {
    return VIBES.find((v) => v.value === (vibe || ''))?.label ?? vibe
  }
</script>

<div class="mode-playlist-mapper">
  {#each MODE_CONFIG as { mode, label, icon } (mode)}
    {@const entries = mappings[mode] || []}
    <div class="mode-playlist-row">
      <div class="mode-playlist-mode">
        <span class="mode-playlist-icon">{icon}</span>
        <span class="mode-playlist-label">{label}</span>
      </div>
      <div class="mode-playlist-entries">
        {#each entries as entry (entry.id)}
          <div class="mode-playlist-entry">
            <span class="entry-title">{entry.favorite_title}</span>
            {#if entry.vibe}
              <span class="entry-vibe">{vibeLabel(entry.vibe)}</span>
            {/if}
            <span class="entry-auto" class:auto-on={entry.auto_play} class:auto-off={!entry.auto_play}>
              {entry.auto_play ? 'Auto' : 'Manual'}
            </span>
            <button class="icon-btn remove-btn" on:click={() => handleRemove(mode, entry.id)} title="Remove">×</button>
          </div>
        {/each}
        {#if favorites.length > 0}
          <div class="mode-playlist-add-row">
            <select
              class="setting-select mode-playlist-select"
              bind:value={addRowState[mode].title}
            >
              <option value="">Add favorite…</option>
              {#each favorites as fav (fav.title)}
                <option value={fav.title}>{fav.title}</option>
              {/each}
            </select>
            <select
              class="setting-select vibe-select"
              bind:value={addRowState[mode].vibe}
              disabled={!addRowState[mode].title}
            >
              {#each VIBES as v (v.value)}
                <option value={v.value}>{v.label}</option>
              {/each}
            </select>
            <button
              class="toggle-btn"
              class:toggle-on={addRowState[mode].autoPlay}
              on:click={() => { addRowState[mode].autoPlay = !addRowState[mode].autoPlay; addRowState = { ...addRowState } }}
              disabled={!addRowState[mode].title}
              title={addRowState[mode].autoPlay ? 'Auto-play on mode change' : 'Manual play only'}
            >
              {addRowState[mode].autoPlay ? 'Auto' : 'Manual'}
            </button>
            <button
              class="icon-btn add-btn"
              on:click={() => handleAdd(mode)}
              disabled={!addRowState[mode].title || addRowState[mode].saving}
              title="Add mapping"
            >
              +
            </button>
          </div>
        {/if}
      </div>
    </div>
  {/each}
  {#if favorites.length === 0}
    <p class="mode-playlist-hint">
      No Sonos favorites found. Add playlists in the Sonos app, then map them here.
    </p>
  {/if}
</div>

// frontend/src/components/music/ModePlaylistMapper.jsx
import { useState, useEffect, useCallback, memo, useRef } from 'react'

const MODE_CONFIG = [
  { mode: 'gaming', label: 'Gaming', icon: '\uD83C\uDFAE' },
  { mode: 'working', label: 'Working', icon: '\uD83D\uDCBB' },
  { mode: 'watching', label: 'Watching', icon: '\uD83C\uDFAC' },
  { mode: 'relax', label: 'Relax', icon: '\uD83D\uDECB\uFE0F' },
  { mode: 'social', label: 'Party', icon: '\uD83C\uDF89' },
  { mode: 'movie', label: 'Movie', icon: '\uD83C\uDF7F' },
]

const VIBES = [
  { value: '', label: 'No vibe tag' },
  { value: 'energetic', label: '\u26A1 Energetic' },
  { value: 'focus', label: '\uD83C\uDFAF Focus' },
  { value: 'mellow', label: '\uD83C\uDF19 Mellow' },
  { value: 'background', label: '\uD83C\uDFA7 Background' },
  { value: 'hype', label: '\uD83D\uDD25 Hype' },
]

function AddMappingRow({ mode, favorites, onAdd }) {
  const [title, setTitle] = useState('')
  const [vibe, setVibe] = useState('')
  const [autoPlay, setAutoPlay] = useState(false)
  const [saving, setSaving] = useState(false)

  const handleAdd = async () => {
    if (!title) return
    setSaving(true)
    await onAdd({ mode, favorite_title: title, vibe: vibe || null, auto_play: autoPlay })
    setTitle('')
    setVibe('')
    setAutoPlay(false)
    setSaving(false)
  }

  return (
    <div className="mode-playlist-add-row">
      <select
        className="setting-select mode-playlist-select"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      >
        <option value="">Add favorite…</option>
        {favorites.map((fav) => (
          <option key={fav.title} value={fav.title}>{fav.title}</option>
        ))}
      </select>
      <select
        className="setting-select vibe-select"
        value={vibe}
        onChange={(e) => setVibe(e.target.value)}
        disabled={!title}
      >
        {VIBES.map((v) => (
          <option key={v.value} value={v.value}>{v.label}</option>
        ))}
      </select>
      <button
        className={`toggle-btn ${autoPlay ? 'toggle-on' : ''}`}
        onClick={() => setAutoPlay((p) => !p)}
        disabled={!title}
        title={autoPlay ? 'Auto-play on mode change' : 'Manual play only'}
      >
        {autoPlay ? 'Auto' : 'Manual'}
      </button>
      <button
        className="icon-btn add-btn"
        onClick={handleAdd}
        disabled={!title || saving}
        title="Add mapping"
      >
        +
      </button>
    </div>
  )
}

function MappingEntry({ entry, onRemove }) {
  const vibe = VIBES.find((v) => v.value === (entry.vibe || ''))
  return (
    <div className="mode-playlist-entry">
      <span className="entry-title">{entry.favorite_title}</span>
      {entry.vibe && (
        <span className="entry-vibe">{vibe?.label || entry.vibe}</span>
      )}
      <span className={`entry-auto ${entry.auto_play ? 'auto-on' : 'auto-off'}`}>
        {entry.auto_play ? 'Auto' : 'Manual'}
      </span>
      <button
        className="icon-btn remove-btn"
        onClick={() => onRemove(entry.id)}
        title="Remove"
      >
        ×
      </button>
    </div>
  )
}

export const ModePlaylistMapper = memo(function ModePlaylistMapper() {
  const [mappings, setMappings] = useState({})
  const [favorites, setFavorites] = useState([])
  const mountedRef = useRef(true)

  useEffect(() => {
    mountedRef.current = true
    fetch('/api/music/mode-playlists')
      .then((r) => r.json())
      .then((data) => {
        if (mountedRef.current) {
          setMappings(data.mappings || {})
          setFavorites(data.favorites || [])
        }
      })
      .catch(() => {})
    return () => { mountedRef.current = false }
  }, [])

  const handleAdd = useCallback(async (body) => {
    try {
      const res = await fetch('/api/music/mode-playlists', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      if (!res.ok) return
      const data = await res.json()
      // Add the new entry to local state immediately
      setMappings((prev) => ({
        ...prev,
        [body.mode]: [
          ...(prev[body.mode] || []),
          {
            id: data.id,
            mode: body.mode,
            favorite_title: body.favorite_title,
            vibe: body.vibe || null,
            auto_play: body.auto_play,
            priority: body.priority || 0,
          },
        ],
      }))
    } catch { /* ignore */ }
  }, [])

  const handleRemove = useCallback(async (mode, mappingId) => {
    try {
      await fetch(`/api/music/mode-playlists/${mappingId}`, { method: 'DELETE' })
      setMappings((prev) => ({
        ...prev,
        [mode]: (prev[mode] || []).filter((e) => e.id !== mappingId),
      }))
    } catch { /* ignore */ }
  }, [])

  return (
    <div className="mode-playlist-mapper">
      {MODE_CONFIG.map(({ mode, label, icon }) => {
        const entries = mappings[mode] || []
        return (
          <div key={mode} className="mode-playlist-row">
            <div className="mode-playlist-mode">
              <span className="mode-playlist-icon">{icon}</span>
              <span className="mode-playlist-label">{label}</span>
            </div>
            <div className="mode-playlist-entries">
              {entries.map((entry) => (
                <MappingEntry
                  key={entry.id}
                  entry={entry}
                  onRemove={(id) => handleRemove(mode, id)}
                />
              ))}
              {favorites.length > 0 && (
                <AddMappingRow
                  mode={mode}
                  favorites={favorites}
                  onAdd={handleAdd}
                />
              )}
            </div>
          </div>
        )
      })}
      {favorites.length === 0 && (
        <p className="mode-playlist-hint">
          No Sonos favorites found. Add playlists in the Sonos app, then map them here.
        </p>
      )}
    </div>
  )
})
