// frontend-svelte/src/routes/music/+page.svelte
<script>
  import TasteProfileCard from '$lib/components/TasteProfileCard.svelte'
  import ModePlaylistMapper from '$lib/components/ModePlaylistMapper.svelte'
  import RecommendationPanel from '$lib/components/RecommendationPanel.svelte'

  /** @type {any} */
  export let data = undefined
  /** @type {any} */
  export let params = undefined
  data; params;
</script>

<main class="music-page">
  <section class="section">
    <h2 class="section-title">Taste Profile</h2>
    <TasteProfileCard />
  </section>

  <section class="section">
    <h2 class="section-title">Mode → Playlist Mapping</h2>
    <ModePlaylistMapper />
  </section>

  <section class="section">
    <h2 class="section-title">Discover</h2>
    <RecommendationPanel />
  </section>
</main>

// frontend/src/pages/Music.jsx
import { TasteProfileCard } from '../components/music/TasteProfileCard'
import { ModePlaylistMapper } from '../components/music/ModePlaylistMapper'

export function Music() {
  return (
    <main className="home-page">
      <section className="section">
        <h2 className="section-title">Taste Profile</h2>
        <TasteProfileCard />
      </section>

      <section className="section">
        <h2 className="section-title">Mode Playlists</h2>
        <p className="music-description">
          Map Sonos favorites to activity modes. When a mode activates, the mapped playlist
          auto-plays if Sonos is idle, or you'll get a suggestion to switch.
        </p>
        <ModePlaylistMapper />
      </section>
    </main>
  )
}
