// frontend/src/components/layout/QuickActions.jsx
import { memo, useCallback } from 'react'

/**
 * Quick action strip — top-of-Home one-tap shortcuts.
 *
 * Buttons highlight when their target mode matches the current mode.
 * "All off" hits the lights/all endpoint directly; everything else
 * goes through setManualMode.
 */
export const QuickActions = memo(function QuickActions({ currentMode, onMode }) {
  const allOff = useCallback(async () => {
    try {
      await fetch('/api/lights/all', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ on: false }),
      })
    } catch {
      /* ignore */
    }
  }, [])

  const actions = [
    { id: 'movie', label: 'Movie', mode: 'movie' },
    { id: 'relax', label: 'Relax', mode: 'relax' },
    { id: 'social', label: 'Party', mode: 'social' },
    { id: 'sleeping', label: 'Bedtime', mode: 'sleeping' },
    { id: 'auto', label: 'Auto', mode: 'auto' },
  ]

  return (
    <div className="quick-actions">
      <button className="quick-action quick-action-danger" onClick={allOff}>
        All off
      </button>
      {actions.map((a) => (
        <button
          key={a.id}
          className={`quick-action ${currentMode === a.mode ? 'quick-action-active' : ''}`}
          onClick={() => onMode(a.mode)}
        >
          {a.label}
        </button>
      ))}
    </div>
  )
})

// frontend-svelte/src/lib/components/QuickActions.svelte
<script>
  import { automation } from '$lib/stores/automation.js'
  import { setManualMode } from '$lib/stores/init.js'
  import { apiPost } from '$lib/api.js'

  const ACTIONS = [
    { id: 'movie', label: 'Movie', mode: 'movie' },
    { id: 'relax', label: 'Relax', mode: 'relax' },
    { id: 'social', label: 'Party', mode: 'social' },
    { id: 'sleeping', label: 'Bedtime', mode: 'sleeping' },
    { id: 'auto', label: 'Auto', mode: 'auto' },
  ]

  $: currentMode = $automation.mode

  async function allOff() {
    try {
      await apiPost('/api/lights/all', { on: false })
    } catch {
      /* ignore */
    }
  }
</script>

<div class="quick-actions">
  <button class="quick-action quick-action-danger" on:click={allOff}>All off</button>
  {#each ACTIONS as action}
    <button
      class="quick-action"
      class:quick-action-active={currentMode === action.mode}
      on:click={() => setManualMode(action.mode)}
    >
      {action.label}
    </button>
  {/each}
</div>
