// frontend/src/components/music/RecommendationPanel.jsx
import { useState, useEffect, useCallback, memo } from 'react'
import { RecommendationCard } from './RecommendationCard'

const MODES = [
  { key: 'gaming', label: 'Gaming' },
  { key: 'working', label: 'Working' },
  { key: 'relax', label: 'Relax' },
  { key: 'social', label: 'Party' },
]

export const RecommendationPanel = memo(function RecommendationPanel() {
  const [activeMode, setActiveMode] = useState('gaming')
  const [recs, setRecs] = useState([])
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState(null)

  const fetchRecs = useCallback(async (mode) => {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch(`/api/music/recommendations?mode=${mode}`)
      const data = await res.json()
      setRecs(data.recommendations || [])
      if (data.message) setError(data.message)
    } catch {
      setError('Failed to fetch recommendations')
    }
    setLoading(false)
  }, [])

  useEffect(() => { fetchRecs(activeMode) }, [activeMode, fetchRecs])

  const handleGenerate = useCallback(async () => {
    setGenerating(true)
    setError(null)
    try {
      const res = await fetch(`/api/music/recommendations/generate?mode=${activeMode}`, {
        method: 'POST',
      })
      if (!res.ok) {
        const data = await res.json()
        setError(data.detail || 'Generation failed')
      } else {
        await fetchRecs(activeMode)
      }
    } catch {
      setError('Failed to generate recommendations')
    }
    setGenerating(false)
  }, [activeMode, fetchRecs])

  const handleFeedback = useCallback(async (recId, action) => {
    try {
      await fetch(`/api/music/recommendations/${recId}/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action }),
      })
      // Remove from list optimistically
      setRecs(prev => prev.filter(r => r.id !== recId))
    } catch { /* ignore */ }
  }, [])

  const handlePreview = useCallback(async (previewUrl) => {
    try {
      await fetch('/api/music/preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ preview_url: previewUrl }),
      })
    } catch { /* ignore */ }
  }, [])

  return (
    <div className="rec-panel">
      <div className="rec-tabs">
        {MODES.map(({ key, label }) => (
          <button
            key={key}
            className={`rec-tab ${activeMode === key ? 'rec-tab-active' : ''}`}
            onClick={() => setActiveMode(key)}
          >
            {label}
          </button>
        ))}
      </div>

      <div className="rec-content">
        {loading ? (
          <p className="rec-loading">Loading...</p>
        ) : recs.length > 0 ? (
          <div className="rec-list">
            {recs.map((rec) => (
              <RecommendationCard
                key={rec.id}
                rec={rec}
                onFeedback={handleFeedback}
                onPreview={handlePreview}
              />
            ))}
          </div>
        ) : (
          <div className="rec-empty">
            <p>{error || 'No recommendations yet for this mode.'}</p>
          </div>
        )}

        <button
          className="action-btn rec-generate-btn"
          onClick={handleGenerate}
          disabled={generating}
        >
          {generating ? 'Generating...' : 'Generate Recommendations'}
        </button>
      </div>
    </div>
  )
})

// frontend-svelte/src/lib/components/RecommendationPanel.svelte
<script>
  import RecommendationCard from './RecommendationCard.svelte'
  import { apiPost } from '$lib/api.js'

  const MODES = [
    { key: 'gaming',  label: 'Gaming' },
    { key: 'working', label: 'Working' },
    { key: 'relax',   label: 'Relax' },
    { key: 'social',  label: 'Party' },
  ]

  let activeMode = 'gaming'
  /** @type {any[]} */
  let recs = []
  let loading = false
  let generating = false
  /** @type {string | null} */
  let errMsg = null

  /** @param {string} mode */
  async function fetchRecs(mode) {
    loading = true
    errMsg = null
    try {
      const res = await fetch(`/api/music/recommendations?mode=${mode}`)
      const data = await res.json()
      recs = data.recommendations || []
      if (data.message) errMsg = data.message
    } catch {
      errMsg = 'Failed to fetch recommendations'
    }
    loading = false
  }

  // Re-fetch whenever activeMode changes.
  $: fetchRecs(activeMode)

  async function handleGenerate() {
    generating = true
    errMsg = null
    try {
      const res = await fetch(`/api/music/recommendations/generate?mode=${activeMode}`, { method: 'POST' })
      if (!res.ok) {
        const data = await res.json()
        errMsg = data.detail || 'Generation failed'
      } else {
        await fetchRecs(activeMode)
      }
    } catch {
      errMsg = 'Failed to generate recommendations'
    }
    generating = false
  }

  /** @param {number} recId @param {'liked' | 'dismissed'} action */
  async function handleFeedback(recId, action) {
    try {
      await fetch(`/api/music/recommendations/${recId}/feedback`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action }),
      })
      recs = recs.filter((r) => r.id !== recId)
    } catch {
      /* ignore */
    }
  }

  /** @param {string} previewUrl */
  async function handlePreview(previewUrl) {
    try {
      await apiPost('/api/music/preview', { preview_url: previewUrl })
    } catch {
      /* ignore */
    }
  }
</script>

<div class="rec-panel">
  <div class="rec-tabs">
    {#each MODES as { key, label } (key)}
      <button
        class="rec-tab"
        class:rec-tab-active={activeMode === key}
        on:click={() => (activeMode = key)}
      >
        {label}
      </button>
    {/each}
  </div>

  <div class="rec-content">
    {#if recs.length > 0}
      <!-- Keep the list mounted during refetch so the page doesn't shrink and
           jump the scroll position. Dim it slightly while loading. -->
      <div class="rec-list" class:rec-list-loading={loading}>
        {#each recs as rec (rec.id)}
          <RecommendationCard {rec} onFeedback={handleFeedback} onPreview={handlePreview} />
        {/each}
      </div>
    {:else if loading}
      <p class="rec-loading">Loading...</p>
    {:else}
      <div class="rec-empty">
        <p>{errMsg || 'No recommendations yet for this mode.'}</p>
      </div>
    {/if}

    <button class="action-btn rec-generate-btn" on:click={handleGenerate} disabled={generating}>
      {generating ? 'Generating...' : 'Generate Recommendations'}
    </button>
  </div>
</div>
