// frontend/src/components/common/Slider.jsx
export function Slider({ value, min = 0, max = 100, onChange, label, className = '' }) {
  return (
    <div className={`slider-container ${className}`}>
      {label && <label className="slider-label">{label}</label>}
      <input
        type="range"
        min={min}
        max={max}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        className="slider-input"
      />
      <span className="slider-value">{value}</span>
    </div>
  )
}

// frontend-svelte/src/lib/components/Slider.svelte
<script>
  export let value = 0
  export let min = 0
  export let max = 100
  /** @type {string | undefined} */
  export let label = undefined
  export let className = ''
  /** @type {(v: number) => void} */
  export let onChange = () => {}

  /** @param {Event} e */
  function handle(e) {
    const target = /** @type {HTMLInputElement} */ (e.target)
    onChange(Number(target.value))
  }
</script>

<div class="slider-container {className}">
  {#if label}
    <label class="slider-label">{label}</label>
  {/if}
  <input
    type="range"
    {min}
    {max}
    {value}
    on:input={handle}
    class="slider-input"
  />
  <span class="slider-value">{value}</span>
</div>
